#!/bin/bash

echo "================================================"
echo "PropertyGuru Bypass - Railway Fix Required"
echo "================================================"
echo ""
echo "❌ TEST FAILED: PropertyGuru is currently BLOCKED"
echo ""
echo "🔍 REASON: ENABLE_PLAYWRIGHT_CRAWL is not set to 'true'"
echo ""
echo "================================================"
echo "✅ HOW TO FIX (2 minutes):"
echo "================================================"
echo ""
echo "1. Open Railway Dashboard:"
echo "   👉 https://railway.app/dashboard"
echo ""
echo "2. Select Project:"
echo "   👉 Database_ingestion"
echo ""
echo "3. Click Service:"
echo "   👉 backend"
echo ""
echo "4. Go to Variables tab"
echo ""
echo "5. Click '+ New Variable' and add:"
echo "   Name:  ENABLE_PLAYWRIGHT_CRAWL"
echo "   Value: true"
echo ""
echo "6. Click 'Add' (Railway auto-redeploys)"
echo ""
echo "7. Wait 2-3 minutes for deployment"
echo ""
echo "8. Run this test again:"
echo "   python3 test_crawl.py"
echo ""
echo "================================================"
echo "📊 WHAT WILL HAPPEN:"
echo "================================================"
echo ""
echo "Before (current):"
echo "  ❌ fetch_with_requests → BLOCKED"
echo "  ❌ fetch_with_cloudscraper → BLOCKED"
echo "  ❌ fetch_with_playwright → DISABLED (skipped)"
echo "  ❌ Result: 'No crawlable pages found'"
echo ""
echo "After (with ENABLE_PLAYWRIGHT_CRAWL=true):"
echo "  ❌ fetch_with_requests → BLOCKED"
echo "  ❌ fetch_with_cloudscraper → BLOCKED"
echo "  ✅ fetch_with_playwright → SUCCESS! 🎉"
echo "  ✅ Result: PropertyGuru content retrieved"
echo ""
echo "================================================"
echo "🔗 DIRECT LINKS:"
echo "================================================"
echo ""
echo "Railway Dashboard:"
echo "  https://railway.app/dashboard"
echo ""
echo "Documentation:"
echo "  - ENABLE_BYPASS_NOW.md (complete guide)"
echo "  - RAILWAY_PLAYWRIGHT_SETUP.md (setup guide)"
echo "  - CRAWLER_UPGRADE_SUMMARY.md (what's built)"
echo ""
echo "================================================"
echo ""
echo "⏰ TIME REQUIRED: 2 minutes"
echo "💰 COST: $0 (Playwright is free)"
echo ""
echo "Press ENTER to open Railway Dashboard..."
read -r

# Open Railway dashboard
if command -v open &> /dev/null; then
    open "https://railway.app/dashboard"
elif command -v xdg-open &> /dev/null; then
    xdg-open "https://railway.app/dashboard"
else
    echo "Please open: https://railway.app/dashboard"
fi

echo ""
echo "After setting the variable, run: python3 test_crawl.py"
echo ""
