[build]
builder = "NIXPACKS"
buildCommand = "pip install --no-cache-dir -r backend/requirements.txt && playwright install chromium --with-deps"

[deploy]
startCommand = "cd backend && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
