[build]
builder = "NIXPACKS"
buildCommand = "pip install --no-cache-dir -r backend/requirements.txt"

[deploy]
startCommand = "playwright install chromium --with-deps && cd backend && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
