services:
  - type: web
    name: database-ingestion
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
